# Generated by Django 3.1.7 on 2021-02-28 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counts', models.IntegerField(default=0)),
                ('brand', models.CharField(max_length=120)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.hospital')),
            ],
        ),
        migrations.CreateModel(
            name='VaccineType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='VaccineGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=120)),
                ('age_group', models.IntegerField()),
                ('vaccines', models.ManyToManyField(to='vaccine.Vaccine')),
            ],
        ),
        migrations.AddField(
            model_name='vaccine',
            name='vaccine_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vaccine.vaccinetype'),
        ),
    ]
