# Generated by Django 3.1.3 on 2021-02-24 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccine',
            name='brand',
            field=models.CharField(default='cipla', max_length=120),
            preserve_default=False,
        ),
    ]
